services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    depends_on:
      - mysql
    scale: 1
    ports:
       - 3434:8080
